framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: ~
    php_errors:
        log: true
    cache:
        # Redis
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_DSN)%'
    web_link:
        enabled: true
