pool:
  vmImage: 'Ubuntu 16.04'

variables:
  image_name: 'cyclepath-php:$(Build.BuildId)'
  image_cache: 'cyclepath.azurecr.io/cyclepath-php:$(Build.BuildId)'
  work_path: '/var/www/cyclepath'
  target: 'production'

steps:
  - script: docker build -f Dockerfile -t $(image_name) --build-arg WORKFOLDER=$(work_path) --target $(target) --cache-from=$(image_cache) .
    displayName: 'PHP image build'

  - task: Docker@1
    displayName: 'PHP image push'
    inputs:
      azureContainerRegistry: cyclepath.azurecr.io
      imageName: 'cyclepath-php:$(Build.BuildId)'
      command: push
